apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: infra-hub
spec:
  replicas: 1
  selector: { matchLabels: { app: postgres } }
  template:
    metadata: { labels: { app: postgres } }
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports: [{ containerPort: 5432 }]
          env:
            - { name: POSTGRES_USER,     valueFrom: { secretKeyRef: { name: db-credentials, key: DB_USER } } }
            - { name: POSTGRES_PASSWORD, valueFrom: { secretKeyRef: { name: db-credentials, key: DB_PASSWORD } } }
            - { name: POSTGRES_DB,       valueFrom: { secretKeyRef: { name: db-credentials, key: DB_NAME } } }

          volumeMounts:
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
            - name: pgdata
              mountPath: /var/lib/postgresql/data
              subPath: pgdata          
      volumes:
        - name: init-sql
          configMap:
            name: postgres-init
        - name: pgdata
          persistentVolumeClaim:
            claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres           
  namespace: infra-hub
spec:
  selector: { app: postgres }
  ports: [{ port: 5432, targetPort: 5432 }]

